name: cwoker #自定义名称
catch_rules: #转换规则
    - rule: _ #ClientWorker语法糖，匹配当前域，返回一个域名带端口
      transform_rules:
          - search: \#.+ #在发送请求时匹配#后内容并移除
            type: url #支持url status statusCode，默认url
            replace: ''
          - search: _ #ClientWorker语法糖，匹配与catchrule相同的规则
            action: fetch #正常请求
            fetch:
              engine: fetch #单请求引擎，默认fetch
          - search: (^4|^5) #匹配4XX/5XX状态码
            type: status #在status中匹配
            action: return #直接返回
            return: #返回内容
              body: The GateWay is down!This Page is provided by ClientWorker!
              status: 503
